#!/usr/bin/env bash
# Bash script must accept 2 arguments and outputs the subdomain.

func2 () {
   domain="$2"
   subdomain="$1"
   if [ -n "$subdomain" ]
   then
	   dig "$subdomain.$domain" | awk -v subd="$subdomain" '/ANSWER SECTION:/{getline; printf "The subdomain %s is a %s record and points to %s\n", subd, $4, $5}'
   fi
}

if [ "$#" -eq 2 ]
then
	domain="$1"
	subdomain="$2"
	func2 "$subdomain" "$domain"

elif [ "$#" -eq 1 ]
then
	domain="$1"
	func2 "www" "$domain"
	func2 "lb-01" "$domain"
	func2 "web-01" "$domain"
	func2 "web-02" "$domain"
fi
