#!/usr/bin/env bash
# Bash script that installs and configures HAproxy on lb-01 server.
sudo apt-get update
sudo apt-get install -y haproxy
echo
"frontend http
    bind *:80
    mode http
    default_backend web-backend

backend web-backend
    balance roundrobin
    mode http
    server 278301-web-01 54.160.66.54 check
    server 278301-web-02 34.224.2.3 check" | sudo tee -a /etc/haproxy/haproxy.cfg
sudo service haproxy restart
