#!/usr/bin/env bash
# Bash script that installs and configures HAproxy on lb-01 server.
sudo apt-get install -y software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.4
sudo apt-get update
sudo apt-get install -y haproxy
echo "Enabled=1" >> /etc/default/haproxy
echo "
frontend wheykat
    bind *:80
    mode http
    default_backend web-backend

backend web-backend
    balance roundrobin
    mode http
    server 278301-web-01 54.160.66.54 check
    server 278301-web-02 34.224.2.3 check" >> /etc/haproxy/haproxy.cfg
sudo service haproxy start
sudo service haproxy restart
