#!/usr/bin/env bash
# Bash script that generates a MySQL dump and creates a compressed archive out of it.

passwd="$1"
dt="$(date '+%d-%m-%Y)')"
mysqldump -u root -p "$passwd" --all-databases > backup.sql
tar -czvf "$dt.tar.gz" backup.sql
