#!/usr/bin/env bash
# Script that loops from 1 to 10, and shows bad luck at 4th, good
# luck at 8th iteration and Best school for other iterations

i=1
while ((i <= 10))
do
	if ((i == 4))
	then
		echo "bad luck"
	elif ((i == 8))
	then
		echo "good luck"
	else
		echo "Best School"
	fi
		i=$((i + 1))
done
