#!/usr/bin/env bash
# Bash script that displays numbers from 1 to 20 and for 4th displays
# 4 and then bad luck from China, for 9th displays 9 and then bad
# luck from Japan and for 17th displays 17 and then bad luck from 

i=1
while ((i <= 20))
do
	echo $i
	case $i in
		4)
			echo "bad luck from China"
			;;
		9)
			echo "bad luck from Japan"
			;;
		17)
			echo "bad luck from Italy"
			;;
		esac
			((i++))
done
