#!/usr/bin/env bash
# Displays information about the school file.

s="school"
if [ -e $s ]
then
	echo "$s file exists"
	if [ -s $s ]
	then
		echo "school file is empty"
	else
		echo "school file is not empty"
	fi
	if [ -f $s ]
	then
		echo "$s is a regular file"
	fi
else
	echo "school file does not exist"
fi
